### PR TITLE
Capybara 3 Support

### PR DESCRIPTION
**Pull request by ryansch**
- Relaxes the capybara requirement to allow 3.x
- Method signature updates to match capybara 3
- Use new `submits?` method in `click` to simplify method

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks for the PR. Hm, looks like this failed on Travis of the pretty old versions of ruby we're testing against.

Everything less that 2.3 is end of life'd. Would you mind updating the travis file: https://github.com/jeroenvandijk/capybara-mechanize/blob/4239490d2725dd815c73b56067a01de714bbc90c/.travis.yml#L9-L10

to include 2.3, 2.4, and 2.5? We can see if that helps travis.

**Comment by ryansch** [comment]
@phillbaker I've updated the list of rubies.  What's the intent behind the capybara 2.4 gemfile?  Is that supposed to be newer or older than what's in the gemspec?

**Comment by ryansch** [comment]
Yikes.  Looks like I need to update the test suite.

**Comment by phillbaker** [comment]
Oy, looks like a mess. It looks like Travis isn't pulling in the 3.0 version: https://travis-ci.org/jeroenvandijk/capybara-mechanize/jobs/371859689#L499 ? `submits?` is undefined for these tests?

>  What's the intent behind the capybara 2.4 gemfile? Is that supposed to be newer or older than what's in the gemspec?

Hm, it's coming from https://github.com/jeroenvandijk/capybara-mechanize/pull/62. I think the intent was to test both. For the 3.0 tests, it might be easier to create a 3.0 gemfile and check that `submits?` is defined?

**Comment by ryansch** [comment]
Ping @phillbaker ^

**Comment by phillbaker** [comment]
I'm fine with doing a major version bump and only supporting v3.

**Comment by ryansch** [comment]
Ok so the real problem here is that capybara has switched over to rspec 3 and we're still on 2.  I don't really have time to tackle that right now.

**Comment by phillbaker** [comment]
Oy. Thanks for the update. When I get some time, I'll take a look.

**Comment by phillbaker** [comment]
I've cherry-picked your original commit in e82a008564250728ed037eb85db5deff81e91f2d and released 1.10.0 with compatibility for capybara 3.x. Thanks for starting this @ryansch

**Comment by ryansch** [comment]
@phillbaker It looks like you missed the changes in https://github.com/jeroenvandijk/capybara-mechanize/pull/63/commits/02dc2a0d434c7bddba884a3a883732f368780e96

One of these days we'll get the test suite working.  I've been running these changes in our test suite since early May without issue.

**Comment by phillbaker** [comment]
> we'll get the test suite working

Not sure I follow, he test suite for this gem is passing? Or are you saying your test suite with the mainline of this gem?

> you missed the changes in 02dc2a0

Ah, so I did. Want to cherry-pick on master and PR?

**Pull request closed without merging**
